CREATE TABLE IF NOT EXISTS users (
                       id INT AUTO_INCREMENT PRIMARY KEY,
                       username VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       validts BIGINT NOT NULL,
                       confirmed TINYINT(1) NOT NULL DEFAULT 0,
                       checked TINYINT(1) NOT NULL DEFAULT 0,
                       valid TINYINT(1) NOT NULL DEFAULT 0,
                       UNIQUE INDEX uix_username (username),
                       UNIQUE INDEX uix_email (email),
                       INDEX (validts),
                       INDEX (confirmed),
                       INDEX (valid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);
INSERT INTO users (username, email, validts, confirmed, checked, valid) VALUES (CONCAT('user', FLOOR(RAND() * 10000)), CONCAT('user', FLOOR(RAND() * 10000), '@example.com'), UNIX_TIMESTAMP() + (86400 * RAND() * 10), ROUND(RAND()), ROUND(RAND()), ROUND(RAND())) ON DUPLICATE KEY UPDATE username = VALUES(username), email = VALUES(email), validts = VALUES(validts), confirmed = VALUES(confirmed), checked = VALUES(checked), valid = VALUES(valid);


CREATE TABLE IF NOT EXISTS `check_job_queue` (
                             `id` INT AUTO_INCREMENT PRIMARY KEY,
                             validts BIGINT NOT NULL,
                             email VARCHAR(255) NOT NULL,
                             `status` ENUM('pending', 'processing', 'done', 'failed', 'skipped') NOT NULL DEFAULT 'pending',
                             `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             `started_at` TIMESTAMP NULL DEFAULT NULL,
                             `completed_at` TIMESTAMP NULL DEFAULT NULL,
                            INDEX (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `send_job_queue` (
                             `id` INT AUTO_INCREMENT PRIMARY KEY,
                             validts BIGINT NOT NULL,
                             username VARCHAR(255) NOT NULL,
                             email VARCHAR(255) NOT NULL,
                             `status` ENUM('pending', 'processing', 'done', 'failed', 'skipped') NOT NULL DEFAULT 'pending',
                             `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             `started_at` TIMESTAMP NULL DEFAULT NULL,
                             `completed_at` TIMESTAMP NULL DEFAULT NULL,
                            INDEX (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;